### ISSUE TITLE
Verify status_code

### ISSUE THREAD

**Issue by Issen007** [sppautomation/sppclient#3]
Hi,
I'm playing around to implement parts of the sppclient in to our Django code. 
But I got problems to verify what status code I get from each call with the `sppclient`

Is it possible to get hold of the status call after a query?

Example code snip:
```
session = client.SppSession("https://10.0.0.1, "sppadmin", "passw0rd")
session.login()
test = client.SppAPI(session, 'api/endeavour/log/job').get()
print(test.status_code)

```

**Comment by benjones917** [comment]
Hello,

The client module returns only the json() component of the response object (it is using the 'requests' library). If anything other than the expected response code is returned to the client should raise the requests exception HTTPError, the exception should also have the status code.

If you only need the status code when there is a problem my suggestion would be to use a try/except for HTTPError when making calls to the client. The exception will have the response object on it and the status code will be on there. (Ex: e.response.status_code)

The other option could be adding status code to the return of the get, put, post, etc. methods in the client module but it should still return response.json() at it's base so that the structure of expected data doesn't change.

**Comment by Issen007** [comment]
That is a great idea but that mean I only can get hold of status code 401 and not 500 that mean wrong URL.

**Comment by benjones917** [comment]
This exception should get thrown for any error response code (4xx or 5xx) ... see below for example when trying to get wrong URL (404)

Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spplib.sdk.client as client
>>> session = client.SppSession('https://172.20.2.141', 'x', 'x')
>>> try:
...     resp = client.SppAPI(session, 'some/wrong/url').get()
... except Exception as e:
...     error = e
...
>>> error
HTTPError('404 Client Error:  for url: https://172.20.2.141/some/wrong/url',)
>>> error.response.status_code
404
>>>

**Comment by Issen007** [comment]
This is what I get when I try with the wrong IP to the SPP Server.

```
(SPP_Restapi) chrisp@christian-x1:~/github/cristie/SPP_Restapi$ python spp_test.py
Traceback (most recent call last):
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/spplib/sdk/client.py", line 99, in raise_response_error
    pretty_print(r.json())
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spp_test.py", line 8, in <module>
    session = client.SppSession("https://192.168.99.8", "x", "x")
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/spplib/sdk/client.py", line 148, in __init__
    self.login()
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/spplib/sdk/client.py", line 157, in login
    r = self.conn.post("%s/endeavour/session" % self.sess_url, auth=HTTPBasicAuth(self.username, self.password))
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/requests/sessions.py", line 653, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/spplib/sdk/client.py", line 101, in raise_response_error
    pretty_print(r)
  File "/c/Users/Christian.Petersson/github/cristie/SPP_Restapi/lib/python3.6/site-packages/spplib/sdk/client.py", line 107, in pretty_print
    return logging.info(json.dumps(data, sort_keys=True,indent=4, separators=(',', ': ')))
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Response' is not JSON serializable
```

Code Snip:
```
import requests,json
import spplib.sdk.client as client
requests.packages.urllib3.disable_warnings()
session = client.SppSession("https://192.168.99.8", "x", "x")
try:
    test = client.SppAPI(session, 'api/endeavour/log/job').get()

except Exception as e:
    #status_code = e.response.status_code
    status_code = e
    print(status_code)
```

**Comment by benjones917** [comment]
I can't duplicate issue above with latest client.py but can see why this might be happening ... please try with latest version of code... 

In any case we can't expect a status code back from an invalid URL when creating the session but it should fail with some exception passed up from requests module (it may include a status code depending on what services (if any) are running on that endpoint)

Here's example of calling a couple invalid hosts to create session on my end:

`>>> try:
...     session = client.SppSession('https://172.20.58.60', 'x', 'x')
... except Exception as e:
...     error = e
...
>>> error
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='172.20.58.60', port=443): Max retries exceeded with url: /api/endeavour/session (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5f83c17588>: Failed to establish a new connection: [Errno 111] Connection refused',))",),)
>>> try:
...     session = client.SppSession('https://172.20.123.321', 'x', 'x')
... except Exception as e:
...     error = e
...
>>> error
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='172.20.123.321', port=443): Max retries exceeded with url: /api/endeavour/session (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5f83c17d30>: Failed to establish a new connection: [Errno -2] Name or service not known',))",),)
>>> dir(error)
['__cause__', '__class__', '__context__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__suppress_context__', '__traceback__', '__weakref__', 'args', 'characters_written', 'errno', 'filename', 'filename2', 'request', 'response', 'strerror', 'with_traceback']
>>> dir(error.response)
['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
>>>`

**Comment by Issen007** [comment]
I found a similar issue with another project `django-wiki` and it shows that the pip installation was different version number then was actual announced on github.
I'm using version `0.58` of the `sppclient`.

**Comment by Issen007** [comment]
If I'm using following code snip
```
def session_start(spp_url, spp_username, spp_password):
    try:
        session = client.SppSession(spp_url, spp_username, spp_password)
        session.login()
    except requests.exceptions.HTTPError as err:
        print("HTTP Error: {0}".format(err))
        print("exiting ...")
        sys.exit(1)
    except:
        print("unknown ERROR: ", sys.exc_info()[0])
        print("exiting ...")
        sys.exit(1)
```

Then do I get following issue 

````
unknown ERROR:  <class 'requests.exceptions.ConnectionError'>
exiting ...
```
